name: Hourly Jekyll Build

on:
  schedule:
    - cron: '0 * * * *'  # This will run the action every hour

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js v16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Build Jekyll site
      run: |
        gem install jekyll bundler
        bundle install
        bundle exec jekyll build

    - name: Post Build Cleanup (Optional)
      run: echo "Post build tasks can go here"
      if: runner.os == 'linux'  # This condition can be modified as per your requirements
